### ISSUE TITLE
Extend $partials->get() to support paths

### ISSUE THREAD

**Issue by ivangretsky** [wireframe-framework/wireframe#21]
Good day!

Please extend `$partials->get()` to support paths (see [this forum topic](https://processwire.com/talk/topic/26631-using-partial-with-dash-in-name/) for the context. 

1. Paths relative to the partials root directory should be allowed.
2. I would also wish that we could be able to pass an absolute path not in the partials root directory as a parameter. See [here](https://processwire.com/talk/topic/26643-reuse-views-between-components-and-partials/?do=findComment&comment=220803) for the context.

**Comment by ivangretsky** [comment]
Should `Wireframe::partial()` support that too?

**Comment by teppokoivula** [comment]
Hey @ivangretsky,

Part 1 of this request is implemented in Wireframe 0.22.0.  In order to not break existing API, here's how it works:

```
<?= $partials->get('path/to/partial', [
    'arg1' => 'val1',
]) ?>
```

If arguments array is _not_ provided, the get() method returns Partial object, just like $partials->path->to->partial. You can provide an empty arguments array (`<?= $partials->get('path/to/partial', []) ?>`) if you don't need any arguments, and I've also added a new render method as an alternative:

```
<?= $partials->render('path/to/partial') ?>
```

Wireframe::partial() should also support path syntax like this. In fact it looks like it did already :)

I've updated the docs page for partials to include these new methods: https://wireframe-framework.com/docs/view/partials/.

I only just noticed the second part — and while I do like the idea, I'll have to give this a bit more thought. There are two concerns there: first of all we'd need to properly distinguish between paths, and this is also a (however minor) security concern, i.e. we don't want to accidentally allow embedding anything that wasn't meant to be embedded.

**Comment by teppokoivula** [comment]
@ivangretsky, another update for this issue:

Wireframe 0.23 adds support for the concept of "view namespaces", which should solve part 2 of this request. This allows you to configure one or more namespaces, specify a root folder for each, and then use these to render files from. Currently only partials support namespaces, but I'd like to extend this at least to components too.

I don't have docs up yet, but here's how you'd configure this:

```
// site/config.php

$config->wireframe = [
    'view_namespaces' => [
        'sublayouts' => $config->paths->templates . 'sublayouts/',
    ],
];
```

If you have a file called "basic.php" in your /site/templates/sublayouts/ directory, here's how you could render it:

```
<?= $partials->render('sublayouts::basic') ?>
```

($partials->get() and Wireframe::partial() should work as well.)

Let me know if you run into any issues with this, or if this doesn't seem to make sense to you. Namespace idea was not a part of the original request, but it seems like a sensible way to avoid conflicts, make sure that "unexpected files" can't be accidentally rendered/included, and so on. It's somewhat similar to component namespaces from Blade, actually :)

**Comment by ivangretsky** [comment]
Thanks, @teppokoivula !

As far as I understand, you're not allowing to use partial views from any path due to security reasons. I have cases where view_namespaces could not work (as far as I see it without testing). Like [this one](https://processwire.com/talk/topic/26643-reuse-views-between-components-and-partials/?do=findComment&comment=220800). Would I need to add each component's view folder to view_namespaces to be able to use it?

Is there any reason not to allow any file from `/templates`?

**Comment by teppokoivula** [comment]
@ivangretsky, that's a good point. If you're fine with a bit of verbosity, here's one solution:

```
$config->wireframe = [
    'view_namespaces' => [
        'components' => $config->paths->templates . 'components/',
    ],
];
```

This would enable syntax such as `<?= $partials->render('components::ComponentName/default')`. You can also create a namespace for the templates directory — there's nothing wrong with that, as long as you're aware of it :)

Just for the record security is indeed one reason for current implementation, but it's also about flexibility and simplicity of the syntax: I would like to keep "full" path references out of views, so that the (file / directory) structure of the site is easier to alter later. With namespaces I don't have to provide full path when I request a partial.

Also for the record: my initial version converted paths such as '/some/partial' to '/site/templates/some/partial.php', but from my point of view this seems somewhat prone to error (accidentally prepending slash could have surprising resulta) and fails if I want to refer to a file within a module directory, outside templates directory, or even somewhere else on the filesystem :)

**Comment by ivangretsky** [comment]
Thanks for the explanation. Do you think I should close this issue after testing, or you got other plans to cover on this one?

**Comment by teppokoivula** [comment]
Feel free to leave it open for now. I'll need to update the docs soon, this issue is a good reminder for that. Unless something new pops up by then, I'll likely close the issue at that point :)

**Comment by teppokoivula** [comment]
Initial docs page is now up at https://wireframe-framework.com/docs/view/view-namespaces/, so I'm closing this issue.
